export const FETCH_CATEGORY = "FETCH_CATEGORY"
export const EDIT_CATEGORY = "EDIT_CATEGORY"

export const EDIT_BANNER = "EDIT_BANNER"
export const FETCH_BANNER = "FETCH_BANNER"

export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const FETCH_PRODUCT = "FETCH_PRODUCT"

export const EDIT_PRODUCT_INFO = "EDIT_PRODUCT_INFO"
export const FETCH_PRODUCT_INFO = "FETCH_PRODUCT_INFO"

export const EDIT_PRODUCT_BY_CATEGORY = "EDIT_PRODUCT_BY_CATEGORY"
export const FETCH_PRODUCT_BY_CATEGORY = "FETCH_PRODUCT_BY_CATEGORY"

export const EDIT_SIZE_COLOR = "EDIT_SIZE_COLOR"
export const FETCH_SIZE_COLOR = "FETCH_SIZE_COLOR"

//Giỏ Hàng
export const LIST_ALL_CART = 'LIST_ALL_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CART = 'DELETE_TO_CART';
export const UPDATE_QUANTITY_CART = 'UPDATE_QUANTITY_CART';
export const RESET_CART = 'RESET_CART';

//Get user
export const FETCH_USER = 'FETCH_USER';
export const DELETE_USER = 'DELETE_USER';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const EDIT_USER = 'EDIT_USER';

//Get customer
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const ADD_CUSTOMER_CLIENT = 'ADD_CUSTOMER_CLIENT';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_CLIENT = 'UPDATE_CUSTOMER_CLIENT';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER ';

//Danh Sach Yeu Thich
export const FETCH_PRODUCT_FAVORITE = 'FETCH_PRODUCT_FAVORITE';
export const REMOVE_PRODUCT_FAVORITE = 'REMOVE_PRODUCT_FAVORITE';
export const ADD_PRODUCT_FAVORITE = 'ADD_PRODUCT_FAVORITE';

//Mua
export const FETCH_OBJECT = 'FETCH_OBJECT';
export const FETCH_SECTOR = 'FETCH_SECTOR';

//bill ordered
export const FETCH_BILL_ORDERED = 'FETCH_BILL_ORDERED';
//news
export const FETCH_NEWS = 'FETCH_NEWS';
//rating
export const FETCH_RATING = 'FETCH_RATING';
export const ADD_RATING = 'ADD_RATING';
export const UPDATE_RATING = 'UPDATE_RATING';
export const EDIT_RATING = 'EDIT_RATING ';
