export const FETCH_CATEGORY = "FETCH_CATEGORY"
export const EDIT_CATEGORY = "EDIT_CATEGORY"

export const EDIT_BANNER = "EDIT_BANNER"
export const FETCH_BANNER = "FETCH_BANNER"

export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const FETCH_PRODUCT = "FETCH_PRODUCT"

export const EDIT_PRODUCT_INFO = "EDIT_PRODUCT_INFO"
export const FETCH_PRODUCT_INFO = "FETCH_PRODUCT_INFO"

export const EDIT_PRODUCT_BY_CATEGORY = "EDIT_PRODUCT_BY_CATEGORY"
export const FETCH_PRODUCT_BY_CATEGORY = "FETCH_PRODUCT_BY_CATEGORY"

export const EDIT_SIZE_COLOR = "EDIT_SIZE_COLOR"
export const FETCH_SIZE_COLOR = "FETCH_SIZE_COLOR"

//Giỏ Hàng
export const LIST_ALL_CART = 'LIST_ALL_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CART = 'DELETE_TO_CART';
export const UPDATE_QUANTITY_CART = 'UPDATE_QUANTITY_CART';
export const RESET_CART = 'RESET_CART';


