export const FETCH_CATEGORY = "FETCH_CATEGORY"
export const EDIT_CATEGORY = "EDIT_CATEGORY"

export const EDIT_BANNER = "EDIT_BANNER"
export const FETCH_BANNER = "FETCH_BANNER"

export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const FETCH_PRODUCT = "FETCH_PRODUCT"

